# Exploratory Data Analysis

We want to analyze the data and highlight some simple patterns that matter for modelling using LightGBM, Neural Networks and other advanced models. We might ask some questions about the data:

- Are there many NaN values?
- Which is the data distribution?

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("../data/cubagem_40k_amazon.csv")
df.columns

Index(['asin', 'title', 'main_category', 'source_category', 'categories',
       'store', 'length_cm', 'width_cm', 'height_cm', 'weight_g', 'volume_cm3',
       'density_g_cm3', 'log_volume', 'log_weight', 'dim_max_cm', 'dim_min_cm',
       'dim_ratio', 'price_raw', 'price_numeric', 'log_price', 'avg_rating',
       'n_ratings', 'n_images', 'title_length', 'title_word_count',
       'has_dim_in_title', 'has_size_word_in_title', 'has_qty_in_title',
       'description', 'description_length', 'n_categories_levels', 'image_url',
       'split'],
      dtype='str')

In [21]:
features = {
    "categorical": [
        "main_category",
        "source_category",
        "categories",
        "store",
    ],
    "text": [
        "title",
        "description",
    ],
    "numerical": [
        "price_numeric",
        "avg_rating",
        "n_ratings",
        "n_images",
        "title_length",
        "title_word_count",
        "description_length",
        "n_categories_levels",
    ],
    "title_regex": [
        "has_dim_in_title",
        "has_size_word_in_title",
        "has_qty_in_title",
    ],
    "image": [
        "image_url",
    ],
}

targets = [
    "length_cm",   # length >= width >= height
    "width_cm",
    "height_cm",
    "weight_g",
    "volume_cm3",  # derived: length_cm * width_cm * height_cm
]

In [13]:
df[features["numerical"]].describe()

,price_numeric,avg_rating,n_ratings,n_images,title_length,title_word_count,description_length,n_categories_levels
count,20459.000000,40000.000000,40000.000000,40000.000000,40000.00000,40000.000000,40000.000000,40000.000000
mean,38.895760,4.236365,537.669025,4.993925,112.87230,17.704225,297.305200,4.036600
std,80.286958,0.633111,3933.750320,2.761300,54.41841,8.603188,360.288383,1.407039
min,0.010000,1.000000,1.000000,0.000000,5.00000,1.000000,0.000000,0.000000
25%,11.990000,4.000000,8.000000,2.000000,65.00000,10.000000,0.000000,4.000000
50%,19.990000,4.400000,34.000000,6.000000,109.00000,17.000000,123.000000,4.000000
75%,35.990000,4.600000,164.000000,7.000000,162.00000,25.000000,539.000000,5.000000
max,2999.000000,5.000000,369516.000000,26.000000,742.00000,106.000000,1000.000000,9.000000

In [14]:
df[features["title_regex"]].describe()

       has_dim_in_title has_size_word_in_title has_qty_in_title
count             40000                  40000            40000
unique                2                      2                2
top               False                  False            False
freq              31648                  32807            32236

In [18]:
df[features["categorical"]].describe()

,main_category,source_category,categories,store
count,40000,40000,37302,39468
unique,44,7,4406,25613
top,Amazon Home,Home_and_Kitchen,Toys & Games > Preschool > Pre-Kindergarten Toys,Generic
freq,8704,7825,339,113

In [16]:
df[targets].describe()

          length_cm      width_cm     height_cm      weight_g    volume_cm3
count  40000.000000  40000.000000  40000.000000  40000.000000  4.000000e+04
mean      28.256961     17.775909      7.362241    951.254973  1.091487e+04
std       22.769196     13.889379      7.802568   2873.314349  6.355813e+04
min        1.270000      0.510000      0.510000      1.000000  1.298432e+00
25%       15.240000      8.990000      2.540000     96.390000  4.777763e+02
50%       22.860000     14.990000      5.080000    255.150000  1.571204e+03
75%       32.510000     22.860000      9.197500    662.240000  4.957266e+03
max      200.000000    190.500000    147.320000  49895.120000  3.885701e+06